name: Run Tests of modules

on:
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23.3'

    - name: Download dependencies
      run: go mod download

    - name: Run tests sqlhandler
      run: go test -fuzz=. -fuzztime=2s -v ./driven/sqlhandler
      env:
        MIGRATION_TEST_PATH: ${{ github.workspace }}/driven/sqlhandler/testdata/migrations

    - name: Run tests logformatter
      run: go test -v ./logformatter
      env:
